//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Numero { get; set; }
        public string Nombre { get; set; }
        public int User_Id { get; set; }
        public int Departament_Origen_Id { get; set; }
        public int Departament_Destino_Id { get; set; }
    
        public virtual Departament Departament { get; set; }
        public virtual Departament Departament1 { get; set; }
        public virtual User User { get; set; }
    }
}
